#pragma once

#define CONCAT_SYMBOLS_INNER_2(A,B) A##B
#define CONCAT_SYMBOLS_2(A,B) CONCAT_SYMBOLS_INNER_2(A,B)

#define CONCAT_SYMBOLS_INNER_3(A,B,C) A##B##C
#define CONCAT_SYMBOLS_3(A,B,C) CONCAT_SYMBOLS_INNER_3(A,B,C)

#define CONCAT_SYMBOLS_INNER_4(A,B,C,D) A##B##C##D
#define CONCAT_SYMBOLS_4(A,B,C,D) CONCAT_SYMBOLS_INNER_4(A,B,C,D)