set(c_RootGeneratedDirPath ${CMAKE_CURRENT_BINARY_DIR}/Generated)
set(c_RootSourceDirPath ${c_RootDirPath}/Source)
set(c_RootProjectDirPath ${c_RootDirPath}/Project)
set(c_RootCMakeDirPath ${c_RootDirPath}/CMake)
set(c_RootThirdPartyDirPath ${c_RootDirPath}/ThirdParty)