if(PROJECT_RELEASE)
	set(ZipFileName ${c_ProjectName}.zip)
	set(ZipFilePath ${CMAKE_INSTALL_PREFIX}/${ZipFileName})
	if(EXISTS "${c_ProjectInstalledDirPath}")
		message("Zipping ${c_ProjectName} ...")
		zip_directory(${c_ProjectInstalledDirPath} ${ZipFilePath})
		set(ReleasingFilePath ${c_PlatformReleaseDirPath}/${ZipFileName})
		file(COPY "${ZipFilePath}" DESTINATION "${c_PlatformReleaseDirPath}")
		file(REMOVE "${ZipFilePath}")
	else()
		message(FATAL_ERROR "${c_ProjectInstalledDirPath} does not exist")
	endif()
endif()